// GENERATED from src/exec-proto.ts by scripts/build-executor.mjs — do not edit.
// Protocol between Amber and an executor (D50): request signing, job envelopes, the spec hash.
// Shared verbatim with the standalone executor (client/amber-executor, generated by
// scripts/build-executor.mjs), so this file may only import node built-ins.
//
// Keys
//   executor  Ed25519 (signs every request it makes) + X25519 (receives job inputs). Both public keys
//             are sent at registration; an admin approves them by fingerprint.
//   Amber     its existing Ed25519 signing key (D27) signs every job; the executor pins it at setup.
// A job's code, sandbox policy, parameters and secrets travel encrypted to the executor's X25519 key
// (ephemeral ECDH + HKDF-SHA256 + AES-256-GCM) and the envelope is signed by Amber, so nothing on the
// way (plain HTTP, nginx) can read the secrets or change what runs.
import { createHash, createPublicKey, createPrivateKey, diffieHellman, generateKeyPairSync, hkdfSync, randomBytes, sign, verify, createCipheriv, createDecipheriv } from 'node:crypto';
                                             

export const PROTO = 'amber-exec-v1';
/** Requests older or newer than this are refused (clock skew + replay window). */
export const REQUEST_SKEW_MS = 120_000;
export const EXECUTOR_NAME = /^[a-z0-9][a-z0-9-]{0,31}$/;
export const ENV_NAME = /^[\p{L}\p{N}][\p{L}\p{N}_-]{0,31}$/u;

const sha256 = (b                 ) => createHash('sha256').update(b).digest('hex');

/** Same as Amber's computeSpecHash: what a review approved. */
export function specHashOf(c                                                                      )         {
  return sha256(JSON.stringify({ name: c.name, params: c.params, script: c.script, options: c.options }));
}

export const pubB64 = (k           ) => (k.export({ type: 'spki', format: 'der' })          ).toString('base64');
export const pubFromB64 = (b64        , type                      )            => {
  const k = createPublicKey({ key: Buffer.from(b64, 'base64'), format: 'der', type: 'spki' });
  if (k.asymmetricKeyType !== type) throw new Error(`公钥类型不对：要 ${type}`);
  return k;
};

/** Fingerprint of an executor's two public keys: 64 hex; the first 16 are its id. */
export function fingerprint(signPub        , boxPub        )         { return sha256(`${PROTO}\n${signPub}\n${boxPub}`); }
/** For people: 8 groups of 4, enough to compare by eye. */
export const showFingerprint = (fp        ) => fp.slice(0, 32).match(/.{4}/g) .join(' ');

export function newExecutorKeys()                                      {
  const pem = (k           ) => k.export({ type: 'pkcs8', format: 'pem' })          ;
  return { signKey: pem(generateKeyPairSync('ed25519').privateKey), boxKey: pem(generateKeyPairSync('x25519').privateKey) };
}
export const keyFromPem = (pem        ) => createPrivateKey(pem);

// ---------- signed requests (executor → Amber)

export function requestInput(method        , path        , ts        , nonce        , body        )         {
  return Buffer.from(`${PROTO}\n${method.toUpperCase()}\n${path}\n${ts}\n${nonce}\n${sha256(body)}`);
}

export function signRequest(key           , executorId        , method        , path        , body        )                         {
  const ts = String(Date.now()), nonce = randomBytes(12).toString('hex');
  return { 'x-amber-executor': executorId, 'x-amber-ts': ts, 'x-amber-nonce': nonce, 'x-amber-sig': sign(null, requestInput(method, path, ts, nonce, body), key).toString('base64') };
}

/** Checks signature and freshness. The caller keeps the nonce cache. */
export function verifyRequest(signPub        , h                                    , method        , path        , body        , now = Date.now())       {
  const ts = h['x-amber-ts'] ?? '', nonce = h['x-amber-nonce'] ?? '', sig = h['x-amber-sig'] ?? '';
  if (!/^\d{13}$/.test(ts) || !/^[0-9a-f]{24}$/.test(nonce) || !sig) throw new Error('缺少签名');
  if (Math.abs(now - Number(ts)) > REQUEST_SKEW_MS) throw new Error('请求时间不对（检查两台机器的时钟）');
  if (!verify(null, requestInput(method, path, ts, nonce, body), pubFromB64(signPub, 'ed25519'), Buffer.from(sig, 'base64'))) throw new Error('签名不对');
}

// ---------- job envelopes (Amber → executor)

                                                                                                                                                  

const aad = (jobId        , executor        ) => Buffer.from(`${PROTO}\0job\0${jobId}\0${executor}`);
const signed = (e                          ) => Buffer.from(`${PROTO}\njob\n${e.v}\n${e.jobId}\n${e.executor}\n${e.exp}\n${e.epk}\n${e.iv}\n${e.ct}\n${e.tag}`);

function boxKey(shared        , epk        , recipient        )         {
  return Buffer.from(hkdfSync('sha256', shared, Buffer.from(`${epk}|${recipient}`), Buffer.from(`${PROTO} job key`), 32));
}

export function sealJob(amberKey           , executorId        , executorBoxPub        , jobId        , ttlMs        , payload         )              {
  const eph = generateKeyPairSync('x25519');
  const epk = pubB64(eph.publicKey);
  const key = boxKey(diffieHellman({ privateKey: eph.privateKey, publicKey: pubFromB64(executorBoxPub, 'x25519') }), epk, executorBoxPub);
  const iv = randomBytes(12);
  const c = createCipheriv('aes-256-gcm', key, iv);
  c.setAAD(aad(jobId, executorId));
  const ct = Buffer.concat([c.update(JSON.stringify(payload), 'utf8'), c.final()]);
  const e = { v: 1         , jobId, executor: executorId, exp: Date.now() + ttlMs, epk, iv: iv.toString('base64'), ct: ct.toString('base64'), tag: c.getAuthTag().toString('base64') };
  return { ...e, sig: sign(null, signed(e), amberKey).toString('base64') };
}

/** Verifies Amber's signature, the addressee and the expiry, then decrypts. Throws on anything off. */
export function openJob(amberPub           , myId        , myBoxKey           , e             , now = Date.now())      {
  if (e?.v !== 1 || typeof e.sig !== 'string') throw new Error('任务格式不对');
  const { sig, ...rest } = e;
  if (!verify(null, signed(rest), amberPub, Buffer.from(sig, 'base64'))) throw new Error('任务签名不对');
  if (e.executor !== myId) throw new Error('任务不是派给本执行端的');
  if (!(e.exp > now)) throw new Error('任务已过期');
  const myPub = pubB64(createPublicKey(myBoxKey));
  const key = boxKey(diffieHellman({ privateKey: myBoxKey, publicKey: pubFromB64(e.epk, 'x25519') }), e.epk, myPub);
  const d = createDecipheriv('aes-256-gcm', key, Buffer.from(e.iv, 'base64'));
  d.setAAD(aad(e.jobId, e.executor));
  d.setAuthTag(Buffer.from(e.tag, 'base64'));
  const payload = JSON.parse(Buffer.concat([d.update(Buffer.from(e.ct, 'base64')), d.final()]).toString('utf8'));
  if (payload?.jobId !== e.jobId) throw new Error('任务内容与信封不符');
  return payload;
}

/** Replaces every secret value (4 characters or longer) that appears in text with ***. */
export function redact(text        , values                        )         {
  let out = text;
  for (const v of Object.values(values).filter(v => v.length >= 4).sort((a, b) => b.length - a.length)) out = out.split(v).join('***');
  return out;
}
