// Protocol between Amber and an executor (D50): request signing, job envelopes, the spec hash.
// Shared verbatim with the standalone executor (client/amber-executor, generated by
// scripts/build-executor.mjs), so this file may only import node built-ins.
//
// Keys
//   executor  Ed25519 (signs every request it makes) + X25519 (receives job inputs). Both public keys
//             are sent at registration; an admin approves them by fingerprint.
//   Amber     its existing Ed25519 signing key (D27) signs every job; the executor pins it at setup.
// A job's code, sandbox policy, parameters and secrets travel encrypted to the executor's X25519 key
// (ephemeral ECDH + HKDF-SHA256 + AES-256-GCM) and the envelope is signed by Amber, so nothing on the
// way (plain HTTP, nginx) can read the secrets or change what runs.
import { createHash, createPublicKey, createPrivateKey, diffieHellman, generateKeyPairSync, hkdfSync, randomBytes, sign, verify, createCipheriv, createDecipheriv } from 'node:crypto';
import type { KeyObject } from 'node:crypto';

export const PROTO = 'amber-exec-v1';
/** Requests older or newer than this are refused (clock skew + replay window). */
export const REQUEST_SKEW_MS = 120_000;
export const EXECUTOR_NAME = /^[a-z0-9][a-z0-9-]{0,31}$/;
export const ENV_NAME = /^[\p{L}\p{N}][\p{L}\p{N}_-]{0,31}$/u;

const sha256 = (b: string | Buffer) => createHash('sha256').update(b).digest('hex');

/** Same as Amber's computeSpecHash: what a review approved. */
export function specHashOf(c: { name: string; params: unknown; script: unknown; options: unknown }): string {
  return sha256(JSON.stringify({ name: c.name, params: c.params, script: c.script, options: c.options }));
}

export const pubB64 = (k: KeyObject) => (k.export({ type: 'spki', format: 'der' }) as Buffer).toString('base64');
export const pubFromB64 = (b64: string, type: 'ed25519' | 'x25519'): KeyObject => {
  const k = createPublicKey({ key: Buffer.from(b64, 'base64'), format: 'der', type: 'spki' });
  if (k.asymmetricKeyType !== type) throw new Error(`公钥类型不对：要 ${type}`);
  return k;
};

/** Fingerprint of an executor's two public keys: 64 hex; the first 16 are its id. */
export function fingerprint(signPub: string, boxPub: string): string { return sha256(`${PROTO}\n${signPub}\n${boxPub}`); }
/** For people: 8 groups of 4, enough to compare by eye. */
export const showFingerprint = (fp: string) => fp.slice(0, 32).match(/.{4}/g)!.join(' ');

export function newExecutorKeys(): { signKey: string; boxKey: string } {
  const pem = (k: KeyObject) => k.export({ type: 'pkcs8', format: 'pem' }) as string;
  return { signKey: pem(generateKeyPairSync('ed25519').privateKey), boxKey: pem(generateKeyPairSync('x25519').privateKey) };
}
export const keyFromPem = (pem: string) => createPrivateKey(pem);

// ---------- signed requests (executor → Amber)

export function requestInput(method: string, path: string, ts: string, nonce: string, body: string): Buffer {
  return Buffer.from(`${PROTO}\n${method.toUpperCase()}\n${path}\n${ts}\n${nonce}\n${sha256(body)}`);
}

export function signRequest(key: KeyObject, executorId: string, method: string, path: string, body: string): Record<string, string> {
  const ts = String(Date.now()), nonce = randomBytes(12).toString('hex');
  return { 'x-amber-executor': executorId, 'x-amber-ts': ts, 'x-amber-nonce': nonce, 'x-amber-sig': sign(null, requestInput(method, path, ts, nonce, body), key).toString('base64') };
}

/** Checks signature and freshness. The caller keeps the nonce cache. */
export function verifyRequest(signPub: string, h: Record<string, string | undefined>, method: string, path: string, body: string, now = Date.now()): void {
  const ts = h['x-amber-ts'] ?? '', nonce = h['x-amber-nonce'] ?? '', sig = h['x-amber-sig'] ?? '';
  if (!/^\d{13}$/.test(ts) || !/^[0-9a-f]{24}$/.test(nonce) || !sig) throw new Error('缺少签名');
  if (Math.abs(now - Number(ts)) > REQUEST_SKEW_MS) throw new Error('请求时间不对（检查两台机器的时钟）');
  if (!verify(null, requestInput(method, path, ts, nonce, body), pubFromB64(signPub, 'ed25519'), Buffer.from(sig, 'base64'))) throw new Error('签名不对');
}

// ---------- job envelopes (Amber → executor)

export interface JobEnvelope { v: 1; jobId: string; executor: string; exp: number; epk: string; iv: string; ct: string; tag: string; sig: string }

const aad = (jobId: string, executor: string) => Buffer.from(`${PROTO}\0job\0${jobId}\0${executor}`);
const signed = (e: Omit<JobEnvelope, 'sig'>) => Buffer.from(`${PROTO}\njob\n${e.v}\n${e.jobId}\n${e.executor}\n${e.exp}\n${e.epk}\n${e.iv}\n${e.ct}\n${e.tag}`);

function boxKey(shared: Buffer, epk: string, recipient: string): Buffer {
  return Buffer.from(hkdfSync('sha256', shared, Buffer.from(`${epk}|${recipient}`), Buffer.from(`${PROTO} job key`), 32));
}

export function sealJob(amberKey: KeyObject, executorId: string, executorBoxPub: string, jobId: string, ttlMs: number, payload: unknown): JobEnvelope {
  const eph = generateKeyPairSync('x25519');
  const epk = pubB64(eph.publicKey);
  const key = boxKey(diffieHellman({ privateKey: eph.privateKey, publicKey: pubFromB64(executorBoxPub, 'x25519') }), epk, executorBoxPub);
  const iv = randomBytes(12);
  const c = createCipheriv('aes-256-gcm', key, iv);
  c.setAAD(aad(jobId, executorId));
  const ct = Buffer.concat([c.update(JSON.stringify(payload), 'utf8'), c.final()]);
  const e = { v: 1 as const, jobId, executor: executorId, exp: Date.now() + ttlMs, epk, iv: iv.toString('base64'), ct: ct.toString('base64'), tag: c.getAuthTag().toString('base64') };
  return { ...e, sig: sign(null, signed(e), amberKey).toString('base64') };
}

/** Verifies Amber's signature, the addressee and the expiry, then decrypts. Throws on anything off. */
export function openJob(amberPub: KeyObject, myId: string, myBoxKey: KeyObject, e: JobEnvelope, now = Date.now()): any {
  if (e?.v !== 1 || typeof e.sig !== 'string') throw new Error('任务格式不对');
  const { sig, ...rest } = e;
  if (!verify(null, signed(rest), amberPub, Buffer.from(sig, 'base64'))) throw new Error('任务签名不对');
  if (e.executor !== myId) throw new Error('任务不是派给本执行端的');
  if (!(e.exp > now)) throw new Error('任务已过期');
  const myPub = pubB64(createPublicKey(myBoxKey));
  const key = boxKey(diffieHellman({ privateKey: myBoxKey, publicKey: pubFromB64(e.epk, 'x25519') }), e.epk, myPub);
  const d = createDecipheriv('aes-256-gcm', key, Buffer.from(e.iv, 'base64'));
  d.setAAD(aad(e.jobId, e.executor));
  d.setAuthTag(Buffer.from(e.tag, 'base64'));
  const payload = JSON.parse(Buffer.concat([d.update(Buffer.from(e.ct, 'base64')), d.final()]).toString('utf8'));
  if (payload?.jobId !== e.jobId) throw new Error('任务内容与信封不符');
  return payload;
}

// ---------- relayed service responses (Amber → executor, D52)

/** What Amber signs for a relayed service response: bound to the job and to the executor's request id,
 *  so an on-path party can neither alter the response nor replay it onto another request. */
export function relayResponseInput(jobId: string, reqId: string, r: { ok: boolean; status?: number; contentType?: string; body?: string; error?: string; message?: string }): Buffer {
  return Buffer.from(JSON.stringify([PROTO, 'relay-response', jobId, reqId, r.ok, r.status ?? null, r.contentType ?? '', r.body ?? '', r.error ?? '', r.message ?? '']));
}
export function verifyRelayResponse(amberPub: KeyObject, jobId: string, reqId: string, r: any): boolean {
  if (typeof r?.sig !== 'string') return false;
  return verify(null, relayResponseInput(jobId, reqId, r), amberPub, Buffer.from(r.sig, 'base64'));
}

/** Replaces every secret value (4 characters or longer) that appears in text with ***. */
export function redact(text: string, values: Record<string, string>): string {
  let out = text;
  for (const v of Object.values(values).filter(v => v.length >= 4).sort((a, b) => b.length - a.length)) out = out.split(v).join('***');
  return out;
}
